# Generated by Django 4.2.7 on 2023-12-26 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.TextField(max_length=80)),
                ('categoria', models.PositiveBigIntegerField(choices=[(1, 'Livros'), (2, 'Roupas'), (3, 'Eletrônicos'), (4, 'Bolsas'), (5, 'Acessórios'), (6, 'Calçados'), (7, 'Brinquedos'), (8, 'Decoração'), (9, 'Outros')], default=9)),
                ('estado', models.PositiveBigIntegerField(choices=[(1, 'Novo'), (2, 'Seminovo'), (3, 'Desgastado')], default=3)),
                ('descricao_produto', models.TextField(max_length=500)),
                ('foto_produto', models.ImageField(upload_to='fotos_produto')),
                ('ativo', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=255)),
                ('telefone', models.CharField(max_length=11)),
                ('matricula', models.CharField(max_length=14)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
