# Generated by Django 4.2.7 on 2023-11-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_consubem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.TextField(max_length=80)),
                ('categoria', models.PositiveBigIntegerField(choices=[(1, 'Livros'), (2, 'Roupas'), (3, 'Eletrônicos'), (4, 'Bolsas'), (5, 'Acessórios'), (6, 'Calçados'), (7, 'Brinquedos'), (8, 'Decoração'), (9, 'Outros')], default=9)),
                ('estado', models.PositiveBigIntegerField(choices=[(1, 'Novo'), (2, 'Seminovo'), (3, 'Usado')], default=3)),
                ('descricao_produto', models.TextField(max_length=500)),
            ],
        ),
    ]
