# Generated by Django 4.2.7 on 2023-12-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_consubem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.PositiveBigIntegerField(choices=[('1', 'Livros'), ('2', 'Roupas'), ('3', 'Eletrônicos'), ('4', 'Bolsas'), ('5', 'Acessórios'), ('6', 'Calçados'), ('7', 'Brinquedos'), ('8', 'Decoração'), ('9', 'Outros')], default=9),
        ),
    ]
