# Generated by Django 4.2.7 on 2023-11-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_consubem', '0002_perfil_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='matricula',
            field=models.CharField(max_length=14),
        ),
    ]
