# Generated by Django 4.2.7 on 2023-11-26 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_consubem', '0003_solicitar_troca_produto_foto_produto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='solicitar_troca',
        ),
    ]
