# Generated by Django 4.2.7 on 2023-11-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_consubem', '0004_delete_solicitar_troca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='estado',
            field=models.PositiveBigIntegerField(choices=[(1, 'Novo'), (2, 'Seminovo'), (3, 'Desgastado')], default=3),
        ),
    ]
