# Generated by Django 4.2.7 on 2024-01-04 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_consubem', '0005_ecobag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitar_troca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_troca', models.TextField(max_length=80)),
                ('categoria_troca', models.CharField(choices=[('1', 'Livros'), ('2', 'Roupas'), ('3', 'Eletrônicos'), ('4', 'Bolsas'), ('5', 'Acessórios'), ('6', 'Calçados'), ('7', 'Brinquedos'), ('8', 'Decoração'), ('9', 'Outros')], default='9', max_length=80)),
                ('estado_troca', models.CharField(choices=[('1', 'Novo'), ('2', 'Seminovo'), ('3', 'Desgastado')], default='1', max_length=80)),
                ('descricao_troca', models.TextField(max_length=500)),
                ('foto_troca', models.ImageField(upload_to='fotos_produto')),
                ('ativo', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
