# Generated by Django 4.2.7 on 2023-11-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_consubem', '0005_alter_produto_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_adm', models.TextField(max_length=255)),
                ('matricula', models.CharField(max_length=14, unique=True)),
            ],
        ),
    ]
